### ISSUE TITLE
Make dash-haskell available on stackage

### ISSUE THREAD

**Issue by rgrinberg** [jfeltz/dash-haskell#9]

**Comment by jfeltz** [comment]
Life has me bogged down now. I don't know when I can get to this. I'm in just bug fix mode on this proj. at the moment, though Stackage is still a good idea.

**Comment by hdgarrood** [comment]
The Stackage people now just encourage you to submit packages for inclusion without trying to build Stackage yourself first. I think they use Travis to check it builds ok before accepting packages.

**Comment by jfeltz** [comment]
I've had a chance to look more thoroughly at Stackage and consider submitting. I'm not convinced that those involved have an interest in cultivating a quality focused, responsible,  and sustainable Haskell package ecosystem, commercially or otherwise. I'll revisit this later should there be a dramatic change in leadership & focus on their side. Right now all I see is a group that is doing nothing else but taking mind-share away from an actual solution.
